# Generated by Django 3.2.23 on 2024-01-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
